image: trion/ng-cli-karma

cache:
  paths:
    - web-application/node_modules/

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - cd web-application
        - rm package-lock.json
        - npm install
        - ./node_modules/@angular/cli/bin/ng build --aot --prod
    artifacts:
        paths:
            - web-application/
test:
    stage: test
    script:
        - echo "Testing"
        - test -f "web-application/node_modules/dist/index.html"