stages:
    - dockerBuilder
   
dockerBuilder:
    image: docker:stable
    stage: dockerBuilder
    script:
        - echo "Building docker image"
        - docker status
        - docker login -u josedrojasa -p Hollowichigo428
        - docker build . -t josedrojasa/thesis-front:"$dt"
        - docker push josedrojasa/thesis-front:"$dt"