stages:
    - build
    - test
    - dockerBuilder
   
build:
    image: trion/ng-cli-karma
    stage: build
    script:
        - cd web-application
        - npm install
        - ./node_modules/@angular/cli/bin/ng build --aot --prod
        - rm -rf node_modules
    artifacts:
        paths:
            - web-application/
            
test:
    stage: test
    script:
        - echo "Testing"
        - test -f "web-application/dist/web-application/index.html"

dockerBuilder:
    image: docker:stable
    stage: dockerBuilder
    script:
        - echo "Building docker image"
        - cd web-application
        - dt=$(date '+%Y%m%d%H%M%S');
        - docker login -u josedrojasa -p Hollowichigo428
        - docker build . -t josedrojasa/thesis-front:"$dt"
        - docker push josedrojasa/thesis-front:"$dt"