image: trion/ng-cli-karma

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - cd web-application
        - npm install
        - ./node_modules/@angular/cli/bin/ng build --aot --prod
    artifacts:
        paths:
            - web-application/dist/
test:
    stage: test
    script:
        - echo "Testing"
        - test -f "web-application/dist/index.html"