apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  type: NodePort
  ports:
  - port: 8081
    name: http
  selector:
    app: front
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      containers:
      - name: front
        image: josedrojasa/thesis-front: